# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68ed14ecc8585cc1421dfff8cabc5817c68869e73fb0ccd203554b022ba158a06f4e62cd7de8e0a975ed43b3262241adf6d306a4313887c0e9b43930f40f3bfc

test:
  secret_key_base: 012b41ea2f0081a1e0172fb1940934bf82ca7ac47d4382db7ac9621f61bf963ed8765bd0c12a48a70be705efeb6b1182fe9ddbb4a6c4cd2fcce985c3eeeb0e6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
